CREATE TABLE IF NOT EXISTS leitor (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT NOT NULL, email TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS carteirinha (id INTEGER PRIMARY KEY AUTOINCREMENT, leitor_id INTEGER NOT NULL UNIQUE REFERENCES leitor(id), numero TEXT NOT NULL UNIQUE, emitida_em TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS livro (id INTEGER PRIMARY KEY AUTOINCREMENT, titulo TEXT NOT NULL, isbn TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS autor (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS livro_autor (id INTEGER PRIMARY KEY AUTOINCREMENT, livro_id INTEGER NOT NULL REFERENCES livro(id), autor_id INTEGER NOT NULL REFERENCES autor(id), UNIQUE(livro_id, autor_id));
CREATE TABLE IF NOT EXISTS exemplar (id INTEGER PRIMARY KEY AUTOINCREMENT, livro_id INTEGER NOT NULL REFERENCES livro(id), codigo TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS emprestimo (id INTEGER PRIMARY KEY AUTOINCREMENT, leitor_id INTEGER NOT NULL REFERENCES leitor(id), exemplar_id INTEGER NOT NULL REFERENCES exemplar(id), realizado_em TEXT NOT NULL, previsto_para TEXT NOT NULL CHECK(previsto_para >= realizado_em), devolvido_em TEXT CHECK(devolvido_em IS NULL OR devolvido_em >= realizado_em));
CREATE UNIQUE INDEX IF NOT EXISTS um_emprestimo_ativo ON emprestimo(exemplar_id) WHERE devolvido_em IS NULL;
